# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.SmallIntegerField(choices=[(0, 'Database'), (1, 'ECC System'), (2, 'CRM System')], default=0)),
                ('client', models.CharField(default='000', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseDestination',
            fields=[
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exporter.Destination')),
                ('database_type', models.SmallIntegerField(choices=[(0, 'Microsoft SQL'), (1, 'MYSQL'), (2, 'Java Connector')], default=0)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('port', models.CharField(blank=True, max_length=7)),
                ('database_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SAPDestination',
            fields=[
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exporter.Destination')),
                ('host', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='kb',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.Repository'),
        ),
        migrations.AddField(
            model_name='export',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.Destination'),
        ),
        migrations.AddField(
            model_name='export',
            name='kb',
            field=models.ManyToManyField(to='exporter.KB'),
        ),
    ]
