# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='name',
            field=models.CharField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
