# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0002_export_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
